baseurl = "/"
languageCode = "en-us"
theme = "hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Jérémy Basso homepage"
  keywords = "homepage, blog, science, informatics, development, programming"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"
disableKinds = ["RSS"]

# Social icons
  [[params.social]]
    name = "email"
    url  = "mailto:jeremy.basso.31@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/LokoSama"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/bassojeremy/"

  [languages]
  [languages.en]
    title = "Jérémy Basso"
    homeSubtitle = "Software Engineer"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Jérémy Basso"
      logoHomeLink = "/"
      logoColor = "#12CBF0"

    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About2"
    url        = "/about"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"